version: "3.1"
services:
  db:
    container_name: mysql_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: bank_go
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD:
    ports:
      - "3306:3306"
